### ISSUE TITLE
(load "simple/simple.scm") failed

### ISSUE THREAD

**Issue by wxie2017** [NalaGinrut/simple#1]
Load error:
(load "simple/simple.scm")
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/wxie/work/guile/simple/simple.scm
;;; WARNING: compilation of /home/wxie/work/guile/simple/simple.scm failed:
;;; Invalid terminal or nonterminal:  +

Do you have this problem?
wxie

**Comment by wxie2017** [comment]
(version)
$2 = "2.2.3"

**Comment by NalaGinrut** [comment]
BTW, if you're interested in implementing languages on Guile platform, please watch https://gitlab.com/NalaGinrut/guile-lua-rebirth. I'm writing a paper about it, and will be published on ICFP2018 Schemeworkshop soon. That work will be much serious. Hopefully we can write tutorials on implementing langugaes on Guile.
